### ISSUE TITLE
bug `’’` instead of `dead key` on windows 10 pro

### ISSUE THREAD

**Issue by Asenar** [fabi1cazenave/qwerty-lafayette#72] opened 2018-12-24 18:39 UTC
Hi,

I tried to use qwerty-lafayette on a windows 10 pro, and it's unable to use the `dead key` to make accents.

Pushing that key is equivalent to `’’`. I tried with version 0.5 and 0.6, same problem happens.

**Comment by fabi1cazenave** [comment] 2019-01-03 11:16
Ugh. I don’t have any windows 10 box right now, but I’ll try building a driver with another software to see if it helps. :-(

**Comment by Asenar** [comment] 2019-01-03 13:01
In fact I don't know if this is reproductible : 2 days later (after some lock screen and/or sleep of the laptop) the dead key started to work fine.

**Comment by maggick** [comment] 2019-01-04 08:46
I have a Windows 10 Enterprise and no issues.

**Comment by 20Centimes** [comment] 2019-01-07 17:53
Hello, just to let you know that you are not alone. My dead key does not function properly anymore. Exact same behaviour.
It appeared today, just after a reboot of my PC (Windows 10 Pro). 

I tried to lock screen, sleep and reboot again, without any luck. :(

Maybe a windows update is the cause of  that issue. I'm not sure.

**Comment by 20Centimes** [comment] 2019-01-07 18:02
I just tried the portable version instead of the driver and it works. No issue with the dead key. If I try again the driver, the issue is still there though.

**Comment by z0vsky** [comment] 2019-01-27 13:42
Got the same behaviour reported by @Asenar and @20Centimes using lafayette_windows_v0.6.
No issue with lafayette_pkl_v0.6.

**Environment**:
- OS: Windows 10 Pro 1809
- Hardware: Lenovo Thinkpad x270
- Keyboard: UK QWERTY FRU 01EP024 SUB 01EN548 (ISO pc105 geometry)

I will try to debug this and give feedback if something comes up.

**Comment by nicomro** [comment] 2020-09-17 17:09
Exact same issue here.

**Environment:**
- OS: Windows 10 Familly 2004
- Keyboard: Drop Alt (QWERTY ANSI 67 keys)

**Comment by makz27** [comment] 2021-07-14 18:35
Same issue here

OS : Windows 10 Pro 20H2

**Comment by lenormf** [comment] 2022-01-24 07:32
Does anybody have any workarounds for this?

**Comment by fabi1cazenave** [comment] 2023-01-22 21:43
Can you please check if this still happens with the latest 0.8 drivers for Windows ?
We’re now using KbdEdit to produce the installers, and it seems to give a better result.

**Comment by fabi1cazenave** [comment] 2023-01-27 09:08
Marking this as fixed by #99, feel free to re-open if the problem still occurs.

**Closed by fabi1cazenave** 2023-01-27 09:08 UTC
Labels: bug
