### ISSUE TITLE
On OSX, ~ is not on the key below Esc (with shift)

### ISSUE THREAD

**Issue by YannMoisan** [fabi1cazenave/qwerty-lafayette#5] opened 2014-04-14 20:00 UTC
~ seems to be on <> and not on the key below Esc

**Comment by sonnyp** [comment] 2015-04-05 16:59
Duplicate of https://github.com/fabi1cazenave/qwerty-lafayette/issues/3

**Comment by fabi1cazenave** [comment] 2015-12-05 14:49
Agreed, closing as a dupe. @YannMoisan should come to a tupperVim event so I could try to fix this.

**Closed by fabi1cazenave** 2015-12-05 14:49 UTC
